# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'PickNMix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PickNMix
  pod 'RealmSwift'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'ObjectMapper', '~> 3.4'

  target 'PickNMixTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'

  end

end
